### ISSUE TITLE
Determine board config file from STM32CubeMX

### ISSUE THREAD

**Issue by csann** [elmot/clion-embedded-arm#108]
## Expected Behavior
It would be very helpful if you were able to determine the board configuration file based on the STM32CubeMX project that was imported. If this were done, the projects debug configuration would typically require no user changes. It would also simplify the setup for new users. While there is not much good that can be said about Eclipse, it is able to automatically set this file.

## Actual Behavior
The board config file must be set by the user even though the STM32CubeMX project already knows what board is being used.

**Comment by elmot** [comment]
The feature is partly implemented already, please use CLion 2018.2 EAP and the plugin 1.1.alpha7. The plugin tries to make a guess which file to use during project import.

Unfortunately it's hardly possible to keep the list of boards in sync with OpenOCD, because there are so many boards and openocd is updated every now and then.

Duplicate #54

**Comment by elmot** [comment]
![image](https://user-images.githubusercontent.com/5366945/42695056-e42cb71e-86bc-11e8-9cf5-6e633bf1cde1.png)
It's here

**Comment by csann** [comment]
Yes, I know of that. I’ve also had CLion pop up a dialog box...during importing, it think. Doesn’t happen all the time. 

I’m so happy I don’t have to use Eclipse anymore. Thank you for providing this plugin,
